overrides:
  ceph:
    conf:
      client:
        debug ms: 1
        debug objecter: 20
        debug rados: 20
tasks:
- install:
- ceph:
- workunit:
    clients:
      client.0:
        - rados/stress_watch.sh
